success page created
Zummit-Africa-Inc/Zapi-FE pull request #11
Opened 2022-08-11 17:02 UTC by deviator53

- created success page design

2022-08-11 17:23 UTC, CreedTech approved these changes

2022-08-11 17:23 UTC, CreedTech commented
Approved

2022-08-15 07:42 UTC, Vinyl-Davyl requested changes
Use a Functional Component in the Success page 
I left a comment there

2022-08-15 07:42 UTC, Vinyl-Davyl commented on src/pages/SuccessPage.tsx
> +const SuccessPage = () => {
Use a "const SuccessPage:React.FC = () => {" here

2022-08-15 08:11 UTC, CreedTech reviewed
Functional component

2022-08-15 08:11 UTC, CreedTech commented on src/pages/SuccessPage.tsx
> +const SuccessPage = () => {
Functional component

2022-08-15 09:58 UTC, merged