api redux setup
Zummit-Africa-Inc/Zapi-FE pull request #114
Opened 2022-09-27 09:28 UTC by pablo-clueless

- Added endpoints CRUD operations in redux
- Changed routing for developers

2022-09-27 11:47 UTC, PhilemonBrain requested changes

2022-09-27 11:47 UTC, PhilemonBrain commented on src/App.tsx
> +              <Route path="/developers/api/:id" element={<DeveloperApiPage />} />
change to /developer/api/:id

2022-09-27 11:47 UTC, PhilemonBrain commented on src/App.tsx
>                <Route path="/developers/dashboard" element={<DevDashboard />} />
change to /developer/dashbooard

2022-09-27 11:47 UTC, PhilemonBrain commented on src/components/EndpointTable.tsx
> +  const deleteRoute = (id: string | undefined) => {
you need to make a request to the BE to delete this. once u confirm the deletion, then call the dispatch.

2022-09-27 11:47 UTC, PhilemonBrain commented on src/components/EndpointTable.tsx
> +  const save = (id: string | undefined) => {
you need to make a request to the BE to edit this. once u confirm the edit, then call the dispatch.

2022-09-27 11:47 UTC, PhilemonBrain commented on src/components/EndpointTab.tsx
> +        dispatch(addEndpoint(payload))
we need to make a post request and confirm the request before calling the dispatch

2022-09-28 22:07 UTC, taiwoAkindele commented on src/components/ApiPageLayout/index.tsx
> +       <Navbar id={id} />
Why are you passing an id ?

2022-09-29 08:37 UTC, merged