Org page
Zummit-Africa-Inc/Zapi-FE pull request #15
Opened 2022-08-15 08:11 UTC by Bit-Han

Adding the OrgPage

2022-08-17 23:03 UTC, taiwoAkindele requested changes
Your input field behavior is different from all other input field on the project. Your placeholder should not be shifting to the border on focus. Try to negate that. Also the select box too.

2022-08-17 23:05 UTC, taiwoAkindele commented on src/components/Navbar.tsx
> +  // root: {
Remove if useless

2022-08-17 23:08 UTC, taiwoAkindele commented on src/components/Button.tsx
> +import { height } from '@mui/system';
I think this is a mistake or are you using it anywhere?

2022-08-17 23:09 UTC, taiwoAkindele commented on src/components/Button.tsx
> +import { height } from '@mui/system';
Also you have conflicts on your branch

2022-08-19 08:15 UTC, Bit-Han commented on src/components/Navbar.tsx
> +  // root: {
thanks i have done that

2022-08-19 08:17 UTC, Bit-Han commented on src/components/Button.tsx
> +import { height } from '@mui/system';
yes i have resolved the conflict thanks so much

2022-08-19 13:24 UTC, Temitopefa approved these changes

2022-08-22 08:24 UTC, taiwoAkindele approved these changes

2022-08-25 10:02 UTC, merged