Discussion
Zummit-Africa-Inc/Zapi-FE pull request #267
Opened 2022-11-07 18:53 UTC by CreedTech

- finished api discussion page
- still working on nested API discussions
![Uploading Screenshot 2022-11-07 at 19.36.33.png…]()

2022-11-08 23:06 UTC, CreedTech commented
<img width="1680" alt="Screenshot 2022-11-09 at 00 06 04" src="https://user-images.githubusercontent.com/76216787/200695231-79b42e35-bd26-4755-9d79-111abcb3efe1.png">

2022-11-10 09:01 UTC, pablo-clueless requested changes
The `APIPage` has nothing in it, please move whatever you have in there to `APIMoreInfo`

2022-11-10 09:01 UTC, pablo-clueless commented on src/components/AddChildrenDiscussion.tsx
> +  const { triggerRefresh } = useContextProvider();
This function has become obsolete, dispatch an action instead. Import `getUserApis` and dispatch it after the fetch request

2022-11-10 09:01 UTC, pablo-clueless commented on src/components/AddChildrenDiscussion.tsx
> +      triggerRefresh();
Use `dispatch(getUserApis(profileId))` here instead of manually adding the items to redux. Remove the `triggerRefresh` function

2022-11-10 09:01 UTC, pablo-clueless commented on src/pages/APIMoreInfo.tsx
> +            if (api === undefined || endpoints === undefined) return toast.error('Something went wrong')
Remove the toast here, it will make it throw the error twice

2022-11-10 09:15 UTC, CreedTech commented on src/pages/APIMoreInfo.tsx
> +            if (api === undefined || endpoints === undefined) return toast.error('Something went wrong')
done
please check again

2022-11-10 10:00 UTC, pablo-clueless requested changes

2022-11-10 10:00 UTC, pablo-clueless commented on src/components/AddChildrenDiscussion.tsx
> +      dispatch(getUserApis(profile_id))
This should come last after the `handleUnclicked` function

2022-11-10 10:00 UTC, pablo-clueless commented on src/pages/APIMoreInfo.tsx
> +            console.log({api, endpoints, discussions})
This should look like this:

```
if(api === undefined || endpoints === undefined || discussion === undefined) return
```

This means the request isn't successful

2022-11-10 13:40 UTC, CreedTech commented on src/components/AddChildrenDiscussion.tsx
> +      dispatch(getUserApis(profile_id))
done

2022-11-10 13:40 UTC, CreedTech commented on src/pages/APIMoreInfo.tsx
> +            console.log({api, endpoints, discussions})
done

2022-11-10 22:26 UTC, pablo-clueless approved these changes

2022-11-11 09:18 UTC, PhilemonBrain approved these changes

2022-11-11 09:18 UTC, merged