add test table design done
Zummit-Africa-Inc/Zapi-FE pull request #303
Opened 2022-11-21 17:08 UTC by pablo-clueless

2022-11-22 01:04 UTC, PhilemonBrain requested changes

2022-11-22 01:04 UTC, PhilemonBrain commented on src/components/Tests.tsx
> +                            <div key={index} className={classes.inputs}>
@pablo-clueless we concluded not to use html tags and only mui components, were u having challenges accessing using mui components here?

2022-11-22 06:46 UTC, pablo-clueless commented on src/components/Tests.tsx
> +                            <div key={index} className={classes.inputs}>
I'm not done with it yet. I've changed some of them, it will effect when I push more commit.

2022-11-28 05:34 UTC, taiwoAkindele reviewed
You have conflicts on your branch

2022-12-02 16:30 UTC, merged