made minor fixes
Zummit-Africa-Inc/Zapi-FE pull request #348
Opened 2023-02-13 14:30 UTC by pablo-clueless

2023-02-13 14:39 UTC, PhilemonBrain commented on src/sections/APIHubTab.tsx
> +    "popular apis": <LibraryBooks />,
please revert this.. it'll break on prod

2023-02-13 14:40 UTC, PhilemonBrain commented on src/sections/APIHubTab.tsx
> +    "popular apis": <LibraryBooks />,
and update please

2023-02-13 14:42 UTC, PhilemonBrain requested changes
revert the category name mapping. it'll break on prod

2023-02-13 14:57 UTC, pablo-clueless commented on src/sections/APIHubTab.tsx
> +    "popular apis": <LibraryBooks />,
> please revert this.. it'll break on prod

What will brak on prod??

2023-02-13 15:40 UTC, pablo-clueless commented
> revert the category name mapping. it'll break on prod

Some of the names are not correct and their icons won't show. If the build is successful, will it still break in prod??

2023-02-14 04:30 UTC, PhilemonBrain approved these changes

2023-02-14 04:31 UTC, merged