errors fixed
Zummit-Africa-Inc/Zapi-FE pull request #50
Opened 2022-09-02 12:24 UTC by Temitopefa

fixed errors on naming

2022-09-05 08:06 UTC, pablo-clueless reviewed
Please check for comments

2022-09-05 08:06 UTC, pablo-clueless commented on src/components/Menus.tsx
> +interface Mobile {
If this is to check for screen size, why not just use media query and avoid this trouble??

2022-09-07 12:39 UTC, taiwoAkindele commented on src/assets/index.ts
> +import LinkedInIcon from "./images/linkedin.png";
This will affect production. Return the name to what it was before.

2022-09-07 12:39 UTC, taiwoAkindele commented on src/env.d.ts
> -
should we be able to see this?

2022-09-07 15:46 UTC, taiwoAkindele approved these changes

2022-09-07 16:20 UTC, pablo-clueless requested changes
Delete env.d.ts and create an env file in the root of your project directory.

2022-09-07 16:20 UTC, pablo-clueless commented on src/env.d.ts
> -
This file should be removed, create a .env file in the root of your project directory and put these variables there.

2022-09-07 16:22 UTC, taiwoAkindele commented on src/env.d.ts
> -
@Temitopefa

2022-09-07 16:52 UTC, pablo-clueless approved these changes

2022-09-07 16:53 UTC, PhilemonBrain approved these changes

2022-09-07 16:54 UTC, merged