conditional rendering on Homenavbar page
Zummit-Africa-Inc/Zapi-FE pull request #79
Opened 2022-09-16 17:47 UTC by Bit-Han

2022-09-16 18:08 UTC, pablo-clueless requested changes
Thanks for adding the false state to `isLoggedIn`.


There are typed imports available in the hooks folder. We can't use the normal useSelector and useDispatch.

2022-09-16 18:08 UTC, pablo-clueless commented on src/sections/HomeNavbar.tsx
> +import { useSelector } from "react-redux";
Use the typed selector from `../hooks`

2022-09-16 20:18 UTC, taiwoAkindele approved these changes

2022-09-19 04:04 UTC, PhilemonBrain commented on src/sections/HomeNavbar.tsx
> +import { useSelector } from "react-redux";
@Bit-Han did u compare with the suggestion offered by samsom?

2022-09-19 07:45 UTC, Bit-Han commented on src/sections/HomeNavbar.tsx
> +import { useSelector } from "react-redux";
Thanks samson. i have changed it to the typed selector and dispatch on hooks.

2022-09-19 09:34 UTC, merged