Settingspage
Zummit-Africa-Inc/Zapi-FE pull request #89
Opened 2022-09-21 11:17 UTC by Adebayor7

Created a new branch where i worked on my settings.tsx page

2022-09-21 12:23 UTC, pablo-clueless requested changes
Please remove all the comments from your code, convert syntax to ES6 and add typings

2022-09-21 12:31 UTC, Adebayor7 commented
okay i would do that

2022-09-21 14:17 UTC, PhilemonBrain requested changes

2022-09-21 14:17 UTC, PhilemonBrain commented on src/components/routes/PrivateRoutes.tsx
> -    let auth = {"token": false}
why did u change this?? @Adebayor7

2022-09-21 14:17 UTC, PhilemonBrain commented on src/pages/Settings.tsx
> +//         boxSizing: "border-box"
remove the comments please

2022-09-22 09:19 UTC, Adebayor7 commented on src/pages/Settings.tsx
> +//         boxSizing: "border-box"
Okaay done that

2022-09-23 10:02 UTC, closed without merging