reset password for forgot password flow
Zummit-Africa-Inc/Zapi-FE pull request #92
Opened 2022-09-21 16:47 UTC by deviator53

2022-09-21 19:23 UTC, taiwoAkindele requested changes

2022-09-21 19:23 UTC, taiwoAkindele commented on src/pages/ResetPassword.tsx
> +    const [password, setPassword] = useState("");
set types

2022-09-21 19:23 UTC, taiwoAkindele commented on src/pages/ResetPassword.tsx
> +      const url = `${identity_url}/zapi-identity/auth/reset`;
There is a new env variable, check slack. Only `/reset` should be appended after the url

2022-09-22 08:45 UTC, deviator53 commented on src/pages/ResetPassword.tsx
> +    const [password, setPassword] = useState("");
@taiwoAkindele sorry i don't understand

2022-09-22 09:35 UTC, PhilemonBrain approved these changes

2022-09-22 09:35 UTC, merged