community page added
Zummit-Africa-Inc/Zapi-FE pull request #93
Opened 2022-09-21 19:04 UTC by Gaisensai

2022-09-21 19:17 UTC, taiwoAkindele requested changes
Your branch has none of the existing files. Do a git pull, fix conflicts and push.

2022-09-21 21:55 UTC, pablo-clueless approved these changes

2022-09-25 19:58 UTC, PhilemonBrain commented
@Gaisensai I just viewed it, your ui looks nice, but you need to include this in the tabs specified for it under dashboard. Please reach out to @pablo-clueless if u have any issues

2022-09-26 12:30 UTC, Gaisensai commented
> @Gaisensai I just viewed it, your ui looks nice, but you need to include this in the tabs specified for it under dashboard. Please reach out to @pablo-clueless if u have any issues

2022-09-26 12:30 UTC, closed without merging